set nu
set nocompatible
syntax on
filetype on
filetype plugin on
set shiftwidth=4
set smarttab
set expandtab
set nobackup
set noswapfile
set history=1024
set hlsearch
set incsearch
set nowrapscan
set noerrorbells
set showmatch
colorscheme desert
set background=dark
set smartindent
set ignorecase
set cursorline
set wildignore+=*.png,*.jpg,*.gif,*.ai,*.jpeg,*.psd,*.swp,*.jar,*.zip,*.gem,.DS_Store,log/**,tmp/**,coverage/**,rdoc/**
set gfn=Inconsolata:h13
set fileencodings=UTF-8,GB2312,UTF-16,BIG5
